[versions]
pluginYmlPaperVersion = "0.6.0"
paperApiVersion = "1.21.4-R0.1-SNAPSHOT"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApiVersion" }

[plugins]
pluginYmlPaper = { id = "net.minecrell.plugin-yml.paper", version.ref = "pluginYmlPaperVersion" }